//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubbleAcademico.UI.WUC {
    
    
    public partial class WUC_MENU_LATERAL {
        
        /// <summary>
        /// pnl_usuarioNaoLogado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnl_usuarioNaoLogado;
        
        /// <summary>
        /// pnl_usuarioLogado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnl_usuarioLogado;
        
        /// <summary>
        /// WUC_DOACOES control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HubbleAcademico.UI.WUC.wuc_doacoes WUC_DOACOES;
        
        /// <summary>
        /// WUC_FEEDBACK control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HubbleAcademico.UI.WUC.wuc_modalSugestoes WUC_FEEDBACK;
        
        /// <summary>
        /// WUC_SOBRE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HubbleAcademico.UI.WUC.wuc_modalSobre WUC_SOBRE;
    }
}
