//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubbleAcademico {
    
    
    public partial class Home {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// WUC_NAV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HubbleAcademico.UI.WUC.WUC_HEADER WUC_NAV;
        
        /// <summary>
        /// WUC_MENU_LATERAL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HubbleAcademico.UI.WUC.WUC_MENU_LATERAL WUC_MENU_LATERAL;
        
        /// <summary>
        /// WUC_INFORMACOES_RELEVANTES control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HubbleAcademico.UI.WF.WUC_INFORMACOES_RELEVANTES WUC_INFORMACOES_RELEVANTES;
        
        /// <summary>
        /// WUC_PROGRESSO_DISCIPLINAS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HubbleAcademico.UI.WF.WUC_PROGRESSO_DISCIPLINAS WUC_PROGRESSO_DISCIPLINAS;
        
        /// <summary>
        /// WUC_GRAFICOS_AREAS_CONHECIMENTO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HubbleAcademico.UI.WF.WUC_GRAFICOS_AREAS_CONHECIMENTO WUC_GRAFICOS_AREAS_CONHECIMENTO;
    }
}
